blank_issues_enabled: false
contact_links:
  - name: Official mailing list 
    url: https://groups.google.com/g/reactivemongo
    about: Please ask and answer questions here.
  - name: Community Support (Stack Overflow)
    url: https://stackoverflow.com/questions/tagged/reactivemongo
    about: Please ask and answer questions here.
